COMMENT=	Macro Assembler for Atmel AVR microcontrollers

VER=	1.4.2
PKGNAME=	avra-${VER}
CATEGORIES=	devel

HOMEPAGE=	https://github.com/Ro5bert/avra

# GPLv2
PERMIT_PACKAGE=	Yes

WANTLIB=	c

GH_ACCOUNT=	Ro5bert
GH_PROJECT=	avra
GH_TAGNAME=	${VER}
USE_GMAKE=	Yes

INSTALL_PROGRAM=	avra

.include <bsd.port.mk>
