COMMENT=	BDF format bitmap font file parser library in Python

MODPY_EGG_VERSION=	2.2.0
DISTNAME=	bdfparser-${MODPY_EGG_VERSION}
PKGNAME=	${DISTNAME:S/py/py-/}
CATEGORIES=	devel

# MIT
PERMIT_PACKAGE=	YES

MODPY_PI=	Yes
MODPY_PYBUILD=	setuptools

MODULES=	lang/python

.include <bsd.port.mk>
