COMMENT =	Bear is a tool that generates a compilation database for clang tooling.
GH_ACCOUNT = 	rizsotto
GH_PROJECT = 	Bear
GH_TAGNAME = 	3.1.3
CATEGORIES = 	devel
MAINTAINER =	Artsiom Karakin <karakin2000@gmail.com>

PERMIT_PACKAGE =	YES

COMPILER =	base-clang ports-gcc

BUILD_DEPENDS =		devel/cmake \
			textproc/nlohmann-json	\
				devel/protobuf \
				devel/fmt \
				devel/spdlog

MODULES = 	devel/cmake

.include <bsd.port.mk>
