COMMENT = 	 high-performance remote procedure call (RPC) framework
GH_ACCOUNT =	grpc
GH_PROJECT =	grpc
GH_TAGNAME =	v1.60.0
CATEGORIES = 	devel
MAINTAINER =	Artsiom Karakin <karakin2000@gmail.com>

PERMIT_PACKAGE = 	YES

COMPILER =	base-clang ports-gcc

BUILD_DEPENDS = 	devel/cmake \
			devel/abseil-cpp \
			textproc/re2 \
			devel/protobuf

MODULES = 	devel/cmake

.include <bsd.port.mk>
