COMMENT=	BDF format bitmap font file parser library in Python

MODPY_EGG_VERSION=	2.2.0
DISTNAME=	bdfparser-${MODPY_EGG_VERSION}
PKGNAME=	py-${DISTNAME}
CATEGORIES=	 graphics sysutils

HOMEPAGE=	https://font.tomchen.org/bdfparser_py/

# MIT
PERMIT_PACKAGE=	Yes

MODPY_PI=	Yes
MODPY_PYBUILD=	setuptools

MODULES=	lang/python

.include <bsd.port.mk>
